# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: prednet

dependencies:
  - python=2.7

  - pip:
    - keras==2.0.6
    - theano==0.9.0
    - tensorflow-gpu==1.2.1
    - hickle==2.1.0
    - matplotlib